/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransfersRouteImport } from './routes/_app.transfers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppOrganizationRouteImport } from './routes/_app.organization'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppAuditsRouteImport } from './routes/_app.audits'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAllocationsRouteImport } from './routes/_app.allocations'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsRoute = AppAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAllocationsRoute = AppAllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocations': typeof AppAllocationsRoute
  '/assets': typeof AppAssetsRoute
  '/audits': typeof AppAuditsRoute
  '/bookings': typeof AppBookingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/organization': typeof AppOrganizationRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/transfers': typeof AppTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocations': typeof AppAllocationsRoute
  '/assets': typeof AppAssetsRoute
  '/audits': typeof AppAuditsRoute
  '/bookings': typeof AppBookingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/organization': typeof AppOrganizationRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/transfers': typeof AppTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/allocations': typeof AppAllocationsRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/audits': typeof AppAuditsRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transfers': typeof AppTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocations'
    | '/assets'
    | '/audits'
    | '/bookings'
    | '/dashboard'
    | '/maintenance'
    | '/organization'
    | '/reports'
    | '/settings'
    | '/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocations'
    | '/assets'
    | '/audits'
    | '/bookings'
    | '/dashboard'
    | '/maintenance'
    | '/organization'
    | '/reports'
    | '/settings'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/allocations'
    | '/_app/assets'
    | '/_app/audits'
    | '/_app/bookings'
    | '/_app/dashboard'
    | '/_app/maintenance'
    | '/_app/organization'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits': {
      id: '/_app/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AppAuditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allocations': {
      id: '/_app/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AppAllocationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAllocationsRoute: typeof AppAllocationsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAuditsRoute: typeof AppAuditsRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransfersRoute: typeof AppTransfersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllocationsRoute: AppAllocationsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAuditsRoute: AppAuditsRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransfersRoute: AppTransfersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
